CREATE TABLE tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    description TEXT,
    status TEXT NOT NULL DEFAULT 'pending'
        CHECK (status IN ('pending', 'in_progress', 'completed')),
    due_date DATE,
    image_url TEXT,
    image_public_id TEXT,
    owner_id BIGINT NOT NULL
        REFERENCES users(id) ON DELETE CASCADE
);
